name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare VM
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get --force-yes purge mysql* graphviz* redis*
        sudo apt-get install --assume-yes --quiet git python3-setuptools python3-dev python3-apt ccze tree
    - name: Run WordOps
      run: |
        sudo time bash install --travis
        sudo time bash tests/travis.sh
