name: CI

on:
  push:
    branches:
      - updating-configuration
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  my_job:
    name: test WordOps
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Prepare VM
      run: |
        unset LANG
        sudo apt update -qq > /dev/null 2>&1
        sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y > /dev/null 2>&1
        sudo rm -rf /etc/mysql /var/lib/mysql
        sudo apt-get purge --option=Dpkg::options::=--force-all --assume-yes graphviz* redis* php* mysql* nginx* > /dev/null 2>&1
        sudo apt-get install -qq git ccze tree > /dev/null 2>&1
        sudo apt-get -qq autoremove --purge > /dev/null 2>&1
        sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > $HOME/.gitconfig'
    - name: Install WordOps
      run: sudo timeout 1800 bash install --travis
    - name: Run tests
      run: sudo timeout 1800 bash tests/travis.sh --actions
